services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - '.:/app_name'
    ports:
      - '3000:3000'
    env_file:
      - '.env_docker'