source "https://rubygems.org"

# Specify your gem's dependencies in authentication.gemspec.
gemspec

# Security
gem "bcrypt", "~> 3.1.7" # Password encryption
gem "devise"

# Architecture
gem "dry-validation"
gem "dry-struct"
gem "dry-system", "~> 1"
gem "rails_event_store", "~> 2.2"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false
