source "https://rubygems.org"

# Specify your gem's dependencies in authentication.gemspec.
gemspec

# Security
gem "bcrypt", "~> 3.1.7" # Password encryption
gem "devise"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

gem "dry-validation"
