development:
  adapter: postgresql
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: postgresql
  polling_interval: 0.1.seconds
  message_retention: 1.day
