default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/app_name_development.sqlite3
  cache:
    <<: *default
    database: storage/app_name_development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/app_name_development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/app_name_development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: storage/app_name_test.sqlite3

production:
  primary:
    <<: *default
    database: storage/app_name_production.sqlite3
  cache:
    <<: *default
    database: storage/app_name_production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/app_name_production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/app_name_production_cable.sqlite3
    migrations_paths: db/cable_migrate