service: app_name
image: janeterziev2/app_name

servers:
  web:
    - xx.xx.xx.xx

volumes:
  - "storage:/rails/storage"

proxy:
  ssl: false
  host: xx.xx.xx.xx

registry:
  username: janeterziev2
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ec2-user
  keys: ['ssh/ec2-ssh-key.pem']

builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
    - NEW_RELIC_LICENSE_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"`