name: Deploy to Production

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run_lints_and_security_checks:
    name: 'Run Lints and Security Checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

      - name: Lint code for consistent style
        run: bin/rubocop -f github

#  deploy_production:
#    name: 'Deploy to Production'
#    runs-on: ubuntu-latest
#    environment: Production
#    needs: [run_lints_and_security_checks, run_tests]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: .ruby-version
#          bundler-cache: true
#
#      - name: Install required packages
#        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips
#
#      - name: Add Kamal secrets file
#        run: |
#          mkdir -p .kamal
#          echo "KAMAL_REGISTRY_PASSWORD=${{ secrets.KAMAL_REGISTRY_PASSWORD }}" >> .kamal/secrets
#          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> .kamal/secrets
#          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .kamal/secrets
#          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .kamal/secrets
#          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .kamal/secrets
#          echo "ACTIVE_STORAGE_SERVICE=${{ secrets.ACTIVE_STORAGE_SERVICE }}" >> .kamal/secrets
#          echo "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}" >> .kamal/secrets
#
#      - name: Add SSH key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-ssh-key.pem
#          chmod 600 ~/.ssh/ec2-ssh-key.pem
#
#      - name: Deploy to production with Kamal
#        if: success()
#        run: ./bin/kamal deploy
